### ISSUE TITLE
thank you!The code is very good!

### ISSUE THREAD

**Issue by wuhao13** [Gbps/gbhv#10]
thank you!The code is very good!,but there's a bug in this HvEptHookInstructionMemory !

	//fix bug: fix SizeOfHookedInstructions error!
	PVOID Tmp_TargetFunction = TargetFunction;

	for (SizeOfHookedInstructions = LDE(Tmp_TargetFunction, 64);
		SizeOfHookedInstructions < MaxSizeOfTrampoline;
		SizeOfHookedInstructions += LDE(Tmp_TargetFunction, 64))
	{
		HvUtilLogDebug("LDE Size Code of : %d\n", SizeOfHookedInstructions);
		(INT64)Tmp_TargetFunction = (INT64)Tmp_TargetFunction + LDE(Tmp_TargetFunction, 64);
	}

I hope you can update the compatibility of the code in the latest CPU，thank you！

**Comment by Gbps** [comment]
Thank you for the compliments.

Could you make a pull request with the change so I can review it?

Thank you
