### ISSUE TITLE
BUG HvEptHookWriteAbsoluteJump 

### ISSUE THREAD

**Issue by xorrsp** [Gbps/gbhv#28]
In ept.c

/* Write an absolute x64 jump to an arbitrary address to a buffer. */
VOID HvEptHookWriteAbsoluteJump(PCHAR TargetBuffer, SIZE_T TargetAddress)
{

	/* mov r11, Target */
	TargetBuffer[0] = 0x49;
	TargetBuffer[1] = 0xBB;

	/* Target */
	*((PSIZE_T)&TargetBuffer[2]) = TargetAddress;

	/* push r11 */
	TargetBuffer[10] = 0x41;
	TargetBuffer[11] = 0x53;

	/* ret */
	TargetBuffer[12] = 0xC3;
}

r11 is usually used to save rsp at the beginning of the function.
win7 x64 NtCreateFile:
PAGE:000000014037EE5C 4C 8B DC....................................mov     r11, rsp
PAGE:000000014037EE5F 48 81 EC 88 00 00 00.............sub     rsp, 88h
PAGE:000000014037EE66 33 C0............................................xor     eax, eax
PAGE:000000014037EE68 49 89 43 F0............................... mov     [r11-10h], rax;<--------first 16 bytes

PAGE:000000014037EE6C C7 44 24 70 20 00 00 00......mov     [rsp+88h+var_18], 20h 
PAGE:000000014037EE74 89 44 24 68................................mov     dword ptr [rsp+88h+var_20], eax 
PAGE:000000014037EE78 49 89 43 D8...............................mov     [r11-28h], rax;<---------use r11,BSOD
PAGE:000000014037EE7C 89 44 24 58...............................mov     [rsp+88h+var_30], eax 

VOID HvEptHookWriteAbsoluteJump(PCHAR TargetBuffer, SIZE_T TargetAddress)
{

    /**
     *   Use 'push ret' instead of 'jmp qword[rip+0]',
     *   Because 'jmp qword[rip+0]' will read hooked page 8bytes.
     *
     *   14 bytes hook:
     *   0x68 0x12345678 ......................push 'low 32bit of TargetAddress'
     *   0xC7 0x44 0x24 0x04 0x12345678........mov dword[rsp + 4], 'high 32bit of TargetAddress'
     *   0xC3..................................ret
     */

    UINT32  Low32;
    UINT32  High32;

    Low32 = (UINT32)TargetAddress;
    High32 = (UINT32)(TargetAddress >> 32);

    /* push 'low 32bit of TargetAddress' */
    TargetBuffer[0] = 0x68;
    *((UINT32*)&TargetBuffer[1]) = Low32;

    /* mov dword[rsp + 4], 'high 32bit of TargetAddress' */
    *((UINT32*)&TargetBuffer[5]) = 0x042444C7;
    *((UINT32*)&TargetBuffer[9]) = High32;

    /* ret */
    TargetBuffer[13] = 0xC3;
}

BOOL HvEptHookInstructionMemory(PVMM_EPT_PAGE_HOOK Hook, PVOID TargetFunction, PVOID HookFunction, PVOID* OrigFunction)
{
    replace 13 to 14
}

**Comment by Gbps** [comment]
Hello! Thank you for the find and fix. Can you submit a pull request so you get appropriate credit? Thank you!

**Comment by xorrsp** [comment]
Thank you for the code, it is very useful to me, has been submitted.

**Comment by Gbps** [comment]
Merged #29
