### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by TSheep** [Gbps/gbhv#3]
Hey, as soon as i load the hypervisor my system lags out completely and stays at 100% usage caused by System and System interrupts. it takes like 20 seconds to load up task manager. no bluescreens and the Createfile hook works fine, the system is just kinda unusable. im on a i7 7700hq, 1809 fully updated windows.
any idea what could cause it? 

im not sure if thats the cause of my problem but are you intentionally saving r14 twice, and dont save r12 in https://github.com/Gbps/gbhv/blob/master/gbhv/archdefs.asm#L39

comparing it to the mentioned ntoskrnl.RtlCaptureContext also shows that there might be a mistake:
![rtlsave](https://user-images.githubusercontent.com/23129753/50264254-10430800-041a-11e9-87a1-9b8691ff14c9.png)

**Comment by Gbps** [comment]
Hey there,

You're right, there is a mistake in that capture context you linked, but that is actually an older capture context function which is not used for the actual context saving (that's in vmxdefs.asm). I'll go ahead and fix that anyways.

I've encountered a similar issue in the past which happened due to a rouge vmexit. Might be related to vmtools. Could you post a DebugView kernel logs for the HV?

Thank you!

**Comment by TSheep** [comment]
I was testing it on my host system, not on a vm. below is the debuglog

[*] HvInitializeAllProcessors: Starting.
[*] Total Processor Count: 8
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f40c0
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#0]: Allocated Context [Context = 0xffffaa0c93e17000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f4510
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#1]: Allocated Context [Context = 0xffffaa0c93309000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f4060
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#2]: Allocated Context [Context = 0xffffaa0c8b9c6000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f4420
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#3]: Allocated Context [Context = 0xffffaa0c913ee000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f4270
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#4]: Allocated Context [Context = 0xffffaa0c91ded000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f43c0
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#5]: Allocated Context [Context = 0xffffaa0c8bfd7000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f4600
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#6]: Allocated Context [Context = 0xffffaa0c90014000]
[DEBUG] OffsetIntoPage: 0x620
[DEBUG] Number of bytes of instruction mem: 14
[DEBUG] Trampoline: 0xffffaa0c842f40f0
[DEBUG] HookFunction: 0xfffff80330b82db0
[*] HvInitializeLogicalProcessor[#7]: Allocated Context [Context = 0xffffaa0c856e7000]
[*] VmcsRevisionNumber: 4
[+] HvEptCheckFeatures: All EPT features present.
[DEBUG] EPT: Number of dynamic ranges: 10
[DEBUG] MTRR Range: Base=0x80000000 End=0xFFFFFFFF Type=0x0
[DEBUG] Total MTRR Ranges Committed: 1
[DEBUG] VmxOnRegion[#0]: (V) 0xffffd601d540b000 / (P) 0x863a5e000 [4]
[DEBUG] VmxOnRegion[#1]: (V) 0xffffd601d5417000 / (P) 0x863a5a000 [4]
[DEBUG] VmxOnRegion[#4]: (V) 0xffffd601d6889000 / (P) 0x863a49000 [4]
[DEBUG] VmxOnRegion[#2]: (V) 0xffffd601d5420000 / (P) 0x863a56000 [4]
[DEBUG] VmxOnRegion[#3]: (V) 0xffffd601d543c000 / (P) 0x863a52000 [4]
[DEBUG] VmxOnRegion[#5]: (V) 0xffffd601d6898000 / (P) 0x863a42000 [4]
[DEBUG] VmxOnRegion[#6]: (V) 0xffffd601d68a7000 / (P) 0x863a31000 [4]
[DEBUG] VmxOnRegion[#7]: (V) 0xffffd601d68b6000 / (P) 0x862393000 [4]
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] GdtRegister: 0xffffe7036cf67360, Base: 0xfffff8032e525fb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e2f5a0, Base: 0xffffd601ce033fb0, Limit: 0x57
[DEBUG] HvSetupVmcsControlFields: VmError = 0
[DEBUG] GdtRegister: 0xffffe70364e679f0, Base: 0xffffd601ce413fb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e4f5a0, Base: 0xffffd601ce128fb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e6f5a0, Base: 0xffffd601ce4a7fb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e3f5a0, Base: 0xffffd601ce0d3fb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e8f5a0, Base: 0xffffd601ce5dffb0, Limit: 0x57
[DEBUG] GdtRegister: 0xffffe70364e7f5a0, Base: 0xffffd601ce54cfb0, Limit: 0x57
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[DEBUG] VmxLaunchProcessor: VMLAUNCH....
[+] HvInitializeAllProcessors: Success.
[DEBUG] EPT Violation => 0x2EB8620
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8B01
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8AB4
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8A0F
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8AB4
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8620
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB8620
[+] Made Exec
[DEBUG] EPT Violation => 0x2EB85B0
[+] Made Exec

**Comment by TSheep** [comment]
The same happens on my other machine with a i9 9900k

**Comment by fayhub** [comment]
I am also having the same problem. With the hypervisor loaded, my system will be completely stagnant, and system and system outages will result in 100% utilization. The system is not available. I am testing on VMware 14.  I am using i7 4770

Single step debugging is as follows:


                  0f01c3          vmresume
Illegal instruction - code c000001d (!!! second chance !!!)
fffffa80`1b2f3527 ff              ???

1: kd> g
Illegal instruction - code c000001d (!!! second chance !!!)
fffffa80`1b2f3527 ff              ???
3: kd> g
Illegal instruction - code c000001d (!!! second chance !!!)
fffffa80`1b2f3527 ff              ???
3: kd> g
Illegal instruction - code c000001d (!!! second chance !!!)
fffffa80`1b2f3527 ff              ???
1: kd> g
Illegal instruction - code c000001d (!!! second chance !!!)
fffffa80`1b2f3527 ff              ???



--- No source files  -----------------------------------------------------------------------
fffffa80`1b2f3527  ???  
fffffa80`1b2f3528  inc dword ptr [rcx+53h] 
fffffa80`1b2f352b  ret  
fffffa80`1b2f352c  cmp dl,0FFh 
fffffa80`1b2f352f  inc dword ptr [rbx] 
fffffa80`1b2f3531  add byte ptr [rdx],cl 
fffffa80`1b2f3533  add dl,byte ptr [rsi+61h] 
fffffa80`1b2f3536  ins dword ptr [rdi],dx 
fffffa80`1b2f3538  add byte ptr [rax],al 
fffffa80`1b2f353a  add dword ptr [rdx],eax 
fffffa80`1b2f353c  add byte ptr [rax],al 
fffffa80`1b2f353e  add byte ptr [rax],al 
fffffa80`1b2f3540  xor byte ptr [rbx+59h],dl 
fffffa80`1b2f3543  sbb eax,dword ptr [rax-4F000006h] 
fffffa80`1b2f3549  push 0FFFFFFFFFA801B47h 
fffffa80`1b2f354e  ???  
fffffa80`1b2f354f  push rax 
fffffa80`1b2f3551  xlat byte ptr [rbx] 
fffffa80`1b2f3552  test al,1Bh 
fffffa80`1b2f3554  cmp dl,0FFh 
fffffa80`1b2f3557  push qword ptr [rax+7] 
fffffa80`1b2f355a  add byte ptr [rax],al 
fffffa80`1b2f355c  add byte ptr [rax],al 
fffffa80`1b2f355e  add byte ptr [rax],al 
fffffa80`1b2f3560  jbe fffffa80`1b2f3569 
fffffa80`1b2f3562  add byte ptr [rax],al 
fffffa80`1b2f3564  add byte ptr [rax],al

**Comment by Jojeev** [comment]
@Gbps @TSheep Any updates on this? My host machine slows to a crawl and is rendered almost useless under the HV.

**Comment by Gbps** [comment]
Unfortunately I never got a full debugger dump of a system where this
happened. Without experiencing it on my end it's difficult to track down
this issue.

Does disabling the EPT hook help?

**Comment by thehlopster** [comment]
The same

> Does disabling the EPT hook help?
>
yes

**Comment by Gbps** [comment]
This bug was fixed in commit c554dea6f0a68a98d59dcb492fbd0d02f3436b1f

Thanks to "Vonnegut" for tracking down the bug and the fix.
