### ISSUE TITLE
project still active?

### ISSUE THREAD

**Issue by lonnietc** [Gbps/gbhv#35]
Hello,

I have an idea where this type of HV might really be useful but am wondering if it is still active before diving in more?

Thanks

**Comment by daaximus** [comment]
No, it is not actively updated and maintained. The last updates were about 2 years ago when xorrsp's changes were merged.

The beauty of open-source is that it enables you to pursue your idea regardless of project activity.

**Comment by Gbps** [comment]
I have no plans to commit new features but that doesn't mean the contents of the repo are stale. The hardware extensions that power this haven't changed in any significant way and if something breaks I don't mind fixing it. Since this is a barebones project, it's up to the developer to add features on top of it.On Jan 20, 2024, at 7:32 AM, LonnieTC ***@***.***> wrote:﻿
Hello,
I have an idea where this type of HV might really be useful but am wondering if it is still active before diving in more?
Thanks

**Comment by lonnietc** [comment]
@daaximus Thanks for the quick reply.

Although the idea is still forming, the core idea is that there is a great interest in ultra-high speed networking and virtual switches by using zero-copy and kernel-bypass methods such as the DPDK (Data Plane Development Kit) similar projects. These project effectively take control of the network directly and send data from user space bypassing the kernel which slows things down.  The problem with DPDK development is that it is only supported by various network cards that you might find in some servers and such but has not evolved for laptops and desktops yet.

It occurred to me that instead of trying to hook into things like the NDIS layer in Windows 10 (x64) and other packet methods for L2 and L3 (OSI) techniques, that just maybe something like GBHV or BitVisor could be a more viable solution since it effectively virtualizes the running OS (Windows, Linux, etc.) and can have direct access to the hardware and drivers before passing packets on to the OS kernel which would in-effect be the same thing as kernel-bypassing for standard commodity systems and just maybe do what I am seeking to increase network speeds.

Just an idea, but I think that it could be interesting to investigate with GBHV maybe.
Thanks again

**Comment by lonnietc** [comment]
Hi All,

Also just wondered, possibly before digging into it heavily, if there were any pre-compiled binaries that I could download for testing?

Probably would have to download and compile it up myself, but sill researching the core idea and looking around, but GBHV looks to be very interesting for this use case, although I am not sure how it might work out yet or what problems could still be encountered.

Best and have a great day
