### ISSUE TITLE
Checking MTTR Range

### ISSUE THREAD

**Issue by ghost** [Gbps/gbhv#4]
Is [this ](https://github.com/Gbps/gbhv/blob/master/gbhv/ept.c#L142) correct way to check if a address is inside of a range?
https://github.com/Gbps/gbhv/blob/master/gbhv/ept.c#L142

```
if(AddressOfPage <= GlobalContext->MemoryRanges[CurrentMtrrRange].PhysicalEndAddress)
{
    if( (AddressOfPage + SIZE_2_MB - 1) >= GlobalContext->MemoryRanges[CurrentMtrrRange].PhysicalBaseAddress )

```

I think it should be following:

```
if((AddressOfPage + SIZE_2_MB - 1) <= GlobalContext->MemoryRanges[CurrentMtrrRange].PhysicalEndAddress)
{
    if( AddressOfPage >= GlobalContext->MemoryRanges[CurrentMtrrRange].PhysicalBaseAddress )

```

That's when a address inside of a range

**Comment by Gbps** [comment]
Hi there,

The purpose of my code is to check if any single byte of the page falls within the MTRR range.

It seems your code checks if the entire page falls within the range, which I do not believe is how the Intel manual wants us to do this. 

If you can provide evidence of the contrary, I'll happily look at changing it.

**Comment by ghost** [comment]
Now I understand, thank you for clarification
