### ISSUE TITLE
gbhv process

### ISSUE THREAD

**Issue by ghost** [Gbps/gbhv#5]
Would it be possible to elevate / protect a process (your own process) with gbhv so you can use basic calls without needing to worry about detection? Such as:

`BOOL ReadProcessMemory(
  HANDLE  hProcess,
  LPCVOID lpBaseAddress,
  LPVOID  lpBuffer,
  SIZE_T  nSize,
  SIZE_T  *lpNumberOfBytesRead
);`
or something like:
`HWND FindWindowA(
  LPCSTR lpClassName,
  LPCSTR lpWindowName
);`

**Comment by Gbps** [comment]
This is not a feature of this project, but how you extend this project is up to you. I do not supply assistance for derivative projects.
