### ISSUE TITLE
Support for more that 64 Cores?

### ISSUE THREAD

**Issue by not-wlan** [Gbps/gbhv#7]
Washing machine be like: 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃 👕🔃👖🔃

**Comment by Gbps** [comment]
Fixed in next release.
